### ISSUE TITLE
OperationalError: no such table: main.auth_user__old

### ISSUE THREAD

**Issue by sucrecacao** [GetStream/django_twitter#32]
When trying to run `python manage.py after_deploy`
I get the following error:

`Traceback (most recent call last):
  File "/home/joe/projet/instatoo2/venv2/lib/python3.7/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/joe/projet/instatoo2/venv2/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 303, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: main.auth_user__old`

I am using python3.7 on a virtualenv. Just change pillow version to the latest ( 6.2  ) in the requirements.txt and I have run `python manage.py collectstatic` before `python manage.py after_deploy`. Otherwise I followed the installation as they are in the readme

**Comment by sucrecacao** [comment]
tried with python 3.6.8 and Pillow 4.3 and got the same error

**Comment by sucrecacao** [comment]
Apparently this is a bug for sqlite.
What worked for me is to update to  Django-2.0.3 and stream-django-1.6.1
